'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.cache_enable:
                  replace-description@: true
                  description: PLUGIN_SHORTCODE_GALLERY.CACHE_ENABLE_DESCRIPTION
